CREATE TABLE IF NOT EXISTS meteorological_data (
    id              SERIAL PRIMARY KEY,
    name            TEXT        NOT NULL,
    datetime        DATE        NOT NULL,
    tempmax         REAL        NOT NULL,
    tempmin         REAL        NOT NULL,
    temp            REAL        NOT NULL,
    feelslikemax    REAL        NOT NULL,
    feelslikemin    REAL        NOT NULL,
    feelslike       REAL        NOT NULL,
    dew             REAL        NOT NULL,
    humidity        REAL        NOT NULL,
    precip          REAL        NOT NULL,
    precipprob      REAL        NOT NULL,
    precipcover     REAL        NOT NULL,
    preciptype      TEXT            NULL,
    snow            REAL            NULL,
    snowdepth       REAL            NULL,
    windgust        REAL        NOT NULL,
    windspeed       REAL        NOT NULL,
    winddir         REAL        NOT NULL,
    sealevelpressure REAL       NOT NULL,
    cloudcover      REAL        NOT NULL,
    visibility      REAL        NOT NULL,
    solarradiation  REAL        NOT NULL,
    solarenergy     REAL        NOT NULL,
    uvindex         REAL        NOT NULL,
    severerisk      REAL        NOT NULL,
    sunrise         TIMESTAMP   NOT NULL,
    sunset          TIMESTAMP   NOT NULL,
    moonphase       REAL        NOT NULL,
    conditions      TEXT        NOT NULL,
    description     TEXT        NOT NULL,
    icon            TEXT        NOT NULL,
    stations        TEXT            NULL
);
